//! The agent's `$HOME` (Phase 2 spec §4.2 step 2): Claude settings with
//! hecaton's hooks, credentials, a seeded `.claude.json`, gh hosts.

use std::path::Path;

use hecaton_api::{CredentialBundle, GitAuth, GitSettings};
use hecaton_core::{AgentId, HookTarget, MaterializeError};
use serde_json::{Map, Value, json};

use crate::fsutil::{ensure_dir, ensure_private_dir, write_atomic};
use crate::layout::AgentPaths;
use crate::quote::sh_quote;

/// Events Claude refuses to deliver over HTTP (verified against claude
/// 2.1.263: "HTTP hooks are not supported for SessionStart/Setup"); these
/// run `hecaton hook-relay` as a `command` hook instead (P3-2).
pub const RELAY_EVENTS: &[&str] = &["SessionStart"];

/// Every Claude Code hook event hecaton listens to. Kept as one list so the
/// daemon and the settings writer agree.
pub const HOOK_EVENTS: &[&str] = &[
    "SessionStart",
    "SessionEnd",
    "UserPromptSubmit",
    "PreToolUse",
    "PostToolUse",
    "Notification",
    "Stop",
    "SubagentStop",
    "PreCompact",
];

pub const REDACTED: &str = "<redacted>";

/// User settings plus the hecaton-owned `hooks` block. Any user `hooks` key
/// was rejected at validation; this overwrites unconditionally anyway.
pub fn render_settings(user: &Value, id: &AgentId, hooks: &HookTarget, relay: &Path) -> Value {
    let mut settings = match user {
        Value::Object(m) => m.clone(),
        _ => Map::new(),
    };
    let url = format!(
        "{}/v1/agents/{}/{}/{}/events",
        hooks.url.trim_end_matches('/'),
        id.fleet,
        id.crew,
        id.agent
    );
    let http = json!([{ "hooks": [{ "type": "http", "url": url, "headers": { "Authorization": format!("Bearer {}", hooks.secret) } }] }]);
    // The relay reads the URL and secret from its environment (set through
    // the nono profile), so this entry carries neither.
    let command = json!([{ "hooks": [{ "type": "command", "command": format!("{} hook-relay", sh_quote(&relay.display().to_string())), "timeout": 10 }] }]);
    let block: Map<String, Value> = HOOK_EVENTS
        .iter()
        .map(|e| {
            let entry = if RELAY_EVENTS.contains(e) {
                command.clone()
            } else {
                http.clone()
            };
            (e.to_string(), entry)
        })
        .collect();
    settings.insert("hooks".to_string(), Value::Object(block));
    Value::Object(settings)
}

/// `home/.gitconfig` (Phase 3 spec §6.3): identity always; the gh credential
/// helper only when the crew may push through gh. `gh` resolves through the
/// agent's mise shims inside the sandbox.
pub fn render_gitconfig(id: &AgentId, git: &GitSettings) -> String {
    let (name, email) = match &git.identity {
        Some(i) => (i.name.clone(), i.email.clone()),
        None => (
            id.to_string(),
            format!("{}@{}.{}.hecaton.invalid", id.agent, id.crew, id.fleet),
        ),
    };
    let mut out =
        format!("# generated by hecaton for {id}\n[user]\n\tname = {name}\n\temail = {email}\n");
    if git.auth == GitAuth::Gh && git.push {
        out.push_str("[credential]\n\thelper = \n\thelper = !gh auth git-credential\n");
    }
    out
}

pub fn render_hosts_yml(token: &str) -> String {
    format!("github.com:\n    oauth_token: {token}\n    git_protocol: https\n")
}

/// Seed that suppresses first-run prompts, overlaid with the account fields
/// the bundle carried (`oauthAccount`, `hasCompletedOnboarding`).
pub fn render_claude_json(account: Option<&Value>) -> Value {
    let mut m = Map::new();
    m.insert("hasCompletedOnboarding".to_string(), json!(true));
    if let Some(Value::Object(a)) = account {
        for (k, v) in a {
            m.insert(k.clone(), v.clone());
        }
    }
    Value::Object(m)
}

pub struct HomeInputs<'a> {
    pub settings: &'a Value,
    pub creds: &'a CredentialBundle,
    pub hooks: &'a HookTarget,
    pub git: &'a GitSettings,
    pub relay: &'a Path,
    pub with_gh: bool,
    pub redact_credentials: bool,
}

fn io_err(id: &AgentId, path: &Path, e: std::io::Error) -> MaterializeError {
    MaterializeError::Io {
        id: id.to_string(),
        path: path.to_path_buf(),
        message: e.to_string(),
    }
}

pub fn write_home(
    id: &AgentId,
    paths: &AgentPaths,
    inputs: &HomeInputs,
) -> Result<(), MaterializeError> {
    // The agent root, its home and its logs hold secrets (settings.json,
    // .credentials.json, hosts.yml) and transcripts: 0700, no group or
    // other access. The rest are ordinary tool directories.
    // `tmp/` is 0700 too: claude checks its temp dir's mode before using it.
    for d in [
        paths.root.clone(),
        paths.home.clone(),
        paths.claude_dir(),
        paths.logs.clone(),
        paths.tmp_dir(),
    ] {
        ensure_private_dir(&d).map_err(|e| io_err(id, &d, e))?;
    }
    for d in [
        paths.gh_dir(),
        paths.xdg_data(),
        paths.xdg_state(),
        paths.xdg_cache(),
        paths.nono_home.clone(),
    ] {
        ensure_dir(&d).map_err(|e| io_err(id, &d, e))?;
    }
    let pretty = |v: &Value| serde_json::to_vec_pretty(v).unwrap_or_default();

    // 0600: the hooks block carries the per-agent bearer secret.
    let settings_path = paths.claude_dir().join("settings.json");
    write_atomic(
        &settings_path,
        &pretty(&render_settings(
            inputs.settings,
            id,
            inputs.hooks,
            inputs.relay,
        )),
        0o600,
    )
    .map_err(|e| io_err(id, &settings_path, e))?;

    let creds_path = paths.claude_dir().join(".credentials.json");
    match (&inputs.creds.claude_credentials, inputs.redact_credentials) {
        (Some(_), true) => write_atomic(&creds_path, &pretty(&json!(REDACTED)), 0o600),
        (Some(c), false) => write_atomic(&creds_path, &pretty(c), 0o600),
        (None, _) => Ok(()),
    }
    .map_err(|e| io_err(id, &creds_path, e))?;

    // Written twice: Claude Code reads `$HOME/.claude.json` by default but
    // `$CLAUDE_CONFIG_DIR/.claude.json` when that variable is set, and the
    // sandbox profile sets it. Phase 3's e2e says which copy is live and
    // the unused one goes then.
    let claude_json_body = pretty(&render_claude_json(inputs.creds.claude_account.as_ref()));
    for p in [
        paths.home.join(".claude.json"),
        paths.claude_dir().join(".claude.json"),
    ] {
        write_atomic(&p, &claude_json_body, 0o600).map_err(|e| io_err(id, &p, e))?;
    }

    if inputs.with_gh
        && let Some(token) = &inputs.creds.gh_token
    {
        let hosts = paths.gh_dir().join("hosts.yml");
        let token = if inputs.redact_credentials {
            REDACTED
        } else {
            token.as_str()
        };
        write_atomic(&hosts, render_hosts_yml(token).as_bytes(), 0o600)
            .map_err(|e| io_err(id, &hosts, e))?;
    }

    // 0600 like the rest of home/: it names the credential helper.
    let gitconfig = paths.home.join(".gitconfig");
    write_atomic(
        &gitconfig,
        render_gitconfig(id, inputs.git).as_bytes(),
        0o600,
    )
    .map_err(|e| io_err(id, &gitconfig, e))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::StateLayout;
    use hecaton_api::{GitAuth, GitIdentity, GitSettings};
    use std::os::unix::fs::PermissionsExt;

    fn id() -> AgentId {
        "payments/backend/alice".parse().unwrap()
    }
    fn hooks() -> HookTarget {
        HookTarget {
            url: "http://127.0.0.1:7643/".into(),
            secret: "s3".into(),
        }
    }

    #[test]
    fn settings_get_http_hooks_except_session_start_which_relays() {
        let v = render_settings(
            &json!({ "model": "opus", "hooks": { "Stop": [] } }),
            &id(),
            &hooks(),
            Path::new("/opt/it's/hecaton"),
        );
        assert_eq!(v["model"], "opus");
        let hooks = v["hooks"].as_object().unwrap();
        assert_eq!(hooks.len(), HOOK_EVENTS.len());
        let h = &hooks["PreToolUse"][0]["hooks"][0];
        assert_eq!(h["type"], "http");
        assert_eq!(
            h["url"],
            "http://127.0.0.1:7643/v1/agents/payments/backend/alice/events"
        );
        assert_eq!(h["headers"]["Authorization"], "Bearer s3");
        assert_eq!(
            hooks["Stop"], hooks["PreToolUse"],
            "user hooks are replaced"
        );
        let s = &hooks["SessionStart"][0]["hooks"][0];
        assert_eq!(s["type"], "command");
        assert_eq!(s["command"], "'/opt/it'\\''s/hecaton' hook-relay");
        assert_eq!(s["timeout"], 10);
        assert!(s.get("url").is_none(), "no secret in the relay entry");
    }

    #[test]
    fn gitconfig_renders_identity_and_helper_only_for_gh_push() {
        let by_default = render_gitconfig(&id(), &GitSettings::default());
        assert_eq!(
            by_default,
            "# generated by hecaton for payments/backend/alice\n[user]\n\tname = payments/backend/alice\n\temail = alice@backend.payments.hecaton.invalid\n[credential]\n\thelper = \n\thelper = !gh auth git-credential\n"
        );
        let named = render_gitconfig(
            &id(),
            &GitSettings {
                identity: Some(GitIdentity {
                    name: "Alice Bot".into(),
                    email: "alice@example.com".into(),
                }),
                ..GitSettings::default()
            },
        );
        assert!(named.contains("\tname = Alice Bot\n\temail = alice@example.com\n"));
        let no_push = render_gitconfig(
            &id(),
            &GitSettings {
                push: false,
                ..GitSettings::default()
            },
        );
        assert!(!no_push.contains("[credential]"));
        let no_auth = render_gitconfig(
            &id(),
            &GitSettings {
                auth: GitAuth::None,
                ..GitSettings::default()
            },
        );
        assert!(!no_auth.contains("[credential]"));
    }

    #[test]
    fn hosts_yml_and_claude_json_render() {
        assert_eq!(
            render_hosts_yml("gho_x"),
            "github.com:\n    oauth_token: gho_x\n    git_protocol: https\n"
        );
        let v = render_claude_json(Some(
            &json!({ "oauthAccount": { "emailAddress": "a@b.c" }, "hasCompletedOnboarding": true }),
        ));
        assert_eq!(v["hasCompletedOnboarding"], true);
        assert_eq!(v["oauthAccount"]["emailAddress"], "a@b.c");
        assert_eq!(
            render_claude_json(None),
            json!({ "hasCompletedOnboarding": true })
        );
    }

    fn creds() -> CredentialBundle {
        CredentialBundle {
            claude_credentials: Some(json!({ "claudeAiOauth": { "accessToken": "sk-SECRET" } })),
            claude_account: Some(json!({ "oauthAccount": { "emailAddress": "a@b.c" } })),
            gh_token: Some("gho_SECRET".into()),
        }
    }

    #[test]
    fn writes_every_file_with_the_right_mode() {
        let dir = tempfile::tempdir().unwrap();
        let layout = StateLayout::from_env(dir.path(), |_| None);
        let paths = layout.agent(&id());
        let c = creds();
        write_home(
            &id(),
            &paths,
            &HomeInputs {
                settings: &json!({ "model": "opus" }),
                creds: &c,
                hooks: &hooks(),
                git: &GitSettings::default(),
                relay: Path::new("/opt/hecaton"),
                with_gh: true,
                redact_credentials: false,
            },
        )
        .unwrap();
        let mode = |p: &Path| std::fs::metadata(p).unwrap().permissions().mode() & 0o777;
        // settings.json holds the per-agent hook bearer secret.
        assert_eq!(mode(&paths.claude_dir().join("settings.json")), 0o600);
        assert_eq!(mode(&paths.claude_dir().join(".credentials.json")), 0o600);
        assert_eq!(mode(&paths.gh_dir().join("hosts.yml")), 0o600);
        assert_eq!(mode(&paths.root), 0o700);
        assert_eq!(mode(&paths.home), 0o700);
        assert_eq!(mode(&paths.logs), 0o700);
        assert_eq!(
            mode(&paths.tmp_dir()),
            0o700,
            "claude refuses a shared temp dir"
        );
        assert_eq!(mode(&paths.home.join(".gitconfig")), 0o600);
        assert!(
            std::fs::read_to_string(paths.home.join(".gitconfig"))
                .unwrap()
                .contains("gh auth git-credential")
        );

        let outer = paths.home.join(".claude.json");
        let inner = paths.claude_dir().join(".claude.json");
        assert_eq!(mode(&outer), 0o600);
        assert_eq!(mode(&inner), 0o600);
        assert_eq!(
            std::fs::read_to_string(&outer).unwrap(),
            std::fs::read_to_string(&inner).unwrap(),
            "both copies of .claude.json are written and identical"
        );
        assert!(
            std::fs::read_to_string(paths.claude_dir().join(".credentials.json"))
                .unwrap()
                .contains("sk-SECRET")
        );
        assert!(
            std::fs::read_to_string(paths.gh_dir().join("hosts.yml"))
                .unwrap()
                .contains("gho_SECRET")
        );
        assert!(paths.nono_home.is_dir());
        assert!(paths.logs.is_dir());
    }

    #[test]
    fn redaction_replaces_secrets_and_no_gh_means_no_hosts_file() {
        let dir = tempfile::tempdir().unwrap();
        let layout = StateLayout::from_env(dir.path(), |_| None);
        let paths = layout.agent(&id());
        let c = creds();
        write_home(
            &id(),
            &paths,
            &HomeInputs {
                settings: &json!({}),
                creds: &c,
                hooks: &hooks(),
                git: &GitSettings::default(),
                relay: Path::new("/opt/hecaton"),
                with_gh: false,
                redact_credentials: true,
            },
        )
        .unwrap();
        let creds_file =
            std::fs::read_to_string(paths.claude_dir().join(".credentials.json")).unwrap();
        assert!(!creds_file.contains("SECRET"));
        assert!(creds_file.contains(REDACTED));
        assert!(!paths.gh_dir().join("hosts.yml").exists());
    }
}
