//! `launch.sh` and the `LaunchPlan` (Phase 2 spec §4.2 step 5). No
//! credential is ever an input here.

use hecaton_api::ClaudeSettings;
use hecaton_core::{AgentId, LaunchPlan, MaterializeError};
use std::collections::BTreeMap;

use crate::fsutil::write_atomic;
use crate::layout::AgentPaths;
use crate::quote::sh_quote;
use crate::tools::ToolPaths;

/// The outer `PATH`: system dirs plus wherever `mise` lives, so `mise exec`
/// inside the sandbox can find itself.
pub fn outer_path(tools: &ToolPaths) -> String {
    let mut p = String::from("/usr/local/bin:/usr/bin:/bin");
    if let Some(dir) = tools.mise.parent() {
        let d = dir.display().to_string();
        if !p.split(':').any(|x| x == d) {
            p.push(':');
            p.push_str(&d);
        }
    }
    p
}

/// `claude.resume` and a kept session to continue.
pub fn wants_continue(settings: &ClaudeSettings, paths: &AgentPaths) -> bool {
    settings.resume
        && std::fs::read_dir(paths.claude_projects())
            .map(|mut d| d.next().is_some())
            .unwrap_or(false)
}

pub fn render_launch(
    paths: &AgentPaths,
    tools: &ToolPaths,
    binary: &str,
    args: &[String],
    resume: bool,
) -> (String, LaunchPlan) {
    let env = BTreeMap::from([
        ("PATH".to_string(), outer_path(tools)),
        ("HOME".to_string(), paths.nono_home.display().to_string()),
    ]);
    let mut argv: Vec<String> = vec![
        tools.nono.display().to_string(),
        "-s".into(),
        "--log-file".into(),
        paths.logs.join("nono.log").display().to_string(),
        "run".into(),
        "--profile".into(),
        paths.profile.display().to_string(),
        "--".into(),
        tools.mise.display().to_string(),
        "exec".into(),
        "--".into(),
        binary.to_string(),
    ];
    argv.extend(args.iter().cloned());
    if resume {
        argv.push("--continue".into());
    }
    let mut script =
        String::from("#!/bin/sh\n# generated by hecaton — safe to run by hand\nexec env -i");
    for (k, v) in &env {
        script.push_str(&format!(" {k}={}", sh_quote(v)));
    }
    script.push_str(" \\\n ");
    for a in &argv {
        script.push(' ');
        script.push_str(&sh_quote(a));
    }
    script.push('\n');
    (
        script,
        LaunchPlan {
            cwd: paths.workspace.clone(),
            env,
            argv,
            script: paths.launch.clone(),
        },
    )
}

pub fn write_launch(
    id: &AgentId,
    paths: &AgentPaths,
    script: &str,
) -> Result<(), MaterializeError> {
    write_atomic(&paths.launch, script.as_bytes(), 0o755).map_err(|e| MaterializeError::Io {
        id: id.to_string(),
        path: paths.launch.clone(),
        message: e.to_string(),
    })
}

/// Port the agent must be allowed to connect to for hooks.
pub fn hooks_port(url: &str) -> u16 {
    let rest = url.split("://").nth(1).unwrap_or(url);
    let host_port = rest.split('/').next().unwrap_or(rest);
    host_port
        .rsplit_once(':')
        .and_then(|(_, p)| p.parse().ok())
        .unwrap_or(if url.starts_with("http://") { 80 } else { 443 })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::StateLayout;
    use std::path::Path;

    fn tools() -> ToolPaths {
        ToolPaths {
            git: "/usr/bin/git".into(),
            gh: "/opt/gh".into(),
            mise: "/opt/mise/bin/mise".into(),
            nono: "/opt/nono".into(),
            tmux: "/opt/tmux".into(),
        }
    }

    #[test]
    fn script_quotes_everything_and_carries_no_secret_inputs() {
        let layout = StateLayout::from_env(Path::new("/h"), |_| None);
        let paths = layout.agent(&"f/c/a".parse().unwrap());
        let (script, plan) = render_launch(
            &paths,
            &tools(),
            "claude",
            &["--verbose".into(), "it's".into()],
            true,
        );
        assert!(script.starts_with("#!/bin/sh\n"));
        assert!(script.contains(
            "exec env -i HOME='/h/.local/state/hecaton/fleets/f/crews/c/agents/a/nono' PATH='/usr/local/bin:/usr/bin:/bin:/opt/mise/bin'"
        ));
        assert!(script.contains("'/opt/nono' '-s' '--log-file'"));
        assert!(script.contains(
            "'run' '--profile' '/h/.local/state/hecaton/fleets/f/crews/c/agents/a/nono-profile.json' '--' '/opt/mise/bin/mise' 'exec' '--' 'claude' '--verbose' 'it'\\''s' '--continue'"
        ));
        assert_eq!(plan.cwd, paths.workspace);
        assert_eq!(plan.script, paths.launch);
        assert_eq!(plan.argv.last().unwrap(), "--continue");
        assert_eq!(plan.env.len(), 2);
    }

    #[test]
    fn wants_continue_needs_resume_and_a_kept_session() {
        let dir = tempfile::tempdir().unwrap();
        let layout = StateLayout::from_env(dir.path(), |_| None);
        let paths = layout.agent(&"f/c/a".parse().unwrap());
        let mut s = ClaudeSettings::default();
        assert!(!wants_continue(&s, &paths));
        s.resume = true;
        assert!(!wants_continue(&s, &paths), "no projects dir yet");
        std::fs::create_dir_all(paths.claude_projects().join("x")).unwrap();
        assert!(wants_continue(&s, &paths));
    }

    #[test]
    fn hooks_port_parses_urls() {
        assert_eq!(hooks_port("https://127.0.0.1:7643"), 7643);
        assert_eq!(hooks_port("https://127.0.0.1:7643/"), 7643);
        assert_eq!(hooks_port("https://example.com"), 443);
        assert_eq!(hooks_port("http://localhost"), 80);
    }
}
