//! The generated nono profile (Phase 2 spec §4.2 step 4, P2-5, P2-7).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use hecaton_core::{AgentId, MaterializeError};
use serde_json::{Value, json};

use crate::fsutil::write_atomic;
use crate::layout::{AgentPaths, CrewPaths, StateLayout};
use crate::tools::{Cmd, ToolPaths};

const SYSTEM_READ: &[&str] = &["/usr", "/lib", "/lib64", "/bin", "/etc"];

/// Paths hecaton grants; user grants that overlap these at a different
/// level are rejected.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Grants {
    pub read: Vec<PathBuf>,
    pub allow: Vec<PathBuf>,
}

pub fn hecaton_grants(paths: &AgentPaths, crew: &CrewPaths, layout: &StateLayout) -> Grants {
    let mut read: Vec<PathBuf> = SYSTEM_READ.iter().map(PathBuf::from).collect();
    read.push(layout.mise_data_dir());
    Grants {
        read,
        allow: vec![
            paths.home.clone(),
            paths.workspace.clone(),
            crew.repo.join(".git"),
        ],
    }
}

fn strs(paths: &[PathBuf]) -> Value {
    Value::Array(
        paths
            .iter()
            .map(|p| Value::String(p.display().to_string()))
            .collect(),
    )
}

/// Base profile ⊕ user block, conflicts rejected first.
pub fn render_profile(
    id: &AgentId,
    grants: &Grants,
    daemon_port: u16,
    env: &BTreeMap<String, String>,
    user: &Value,
) -> Result<Value, MaterializeError> {
    check_conflicts(id, user, grants)?;
    let base = json!({
        "meta": { "name": format!("hecaton-{}-{}-{}", id.fleet, id.crew, id.agent), "description": format!("generated by hecaton for {id}") },
        "filesystem": { "read": strs(&grants.read), "allow": strs(&grants.allow) },
        "workdir": { "access": "none" },
        "network": { "connect_port": [daemon_port] },
        "environment": { "deny_vars": ["*"], "set_vars": env },
    });
    Ok(merge_profile(base, user))
}

/// nono's `extends` rules: arrays append and dedupe, maps recurse, scalars
/// user-wins.
pub fn merge_profile(base: Value, user: &Value) -> Value {
    match (base, user) {
        (Value::Object(mut b), Value::Object(u)) => {
            for (k, v) in u {
                let merged = match b.remove(k) {
                    Some(existing) => merge_profile(existing, v),
                    None => v.clone(),
                };
                b.insert(k.clone(), merged);
            }
            Value::Object(b)
        }
        (Value::Array(mut b), Value::Array(u)) => {
            for v in u {
                if !b.contains(v) {
                    b.push(v.clone());
                }
            }
            Value::Array(b)
        }
        (_, u) => u.clone(),
    }
}

/// Access level of a grant list key.
fn level(key: &str) -> Option<&'static str> {
    match key {
        "read" | "read_file" => Some("read"),
        "allow" | "allow_file" => Some("allow"),
        "write" | "write_file" => Some("write"),
        _ => None,
    }
}

fn overlaps(a: &Path, b: &Path) -> bool {
    a == b || a.starts_with(b) || b.starts_with(a)
}

fn entry_path(v: &Value) -> Option<PathBuf> {
    match v {
        Value::String(s) => Some(PathBuf::from(s)),
        Value::Object(m) => m.get("path").and_then(Value::as_str).map(PathBuf::from),
        _ => None,
    }
}

pub fn check_conflicts(
    id: &AgentId,
    user: &Value,
    grants: &Grants,
) -> Result<(), MaterializeError> {
    let conflict = |path: String, message: String| MaterializeError::SandboxConflict {
        id: id.to_string(),
        path,
        message,
    };
    let Value::Object(u) = user else {
        return Ok(());
    };
    if u.contains_key("environment") {
        return Err(conflict(
            "environment".into(),
            "hecaton-owned; set variables through `env` instead".into(),
        ));
    }
    if u.contains_key("meta") {
        return Err(conflict("meta".into(), "hecaton-owned".into()));
    }
    let Some(fs_value) = u.get("filesystem") else {
        return Ok(());
    };
    let Value::Object(fs) = fs_value else {
        return Err(conflict("filesystem".into(), "expected an object".into()));
    };
    for (key, entries) in fs {
        let Some(user_level) = level(key) else {
            continue;
        };
        let Value::Array(items) = entries else {
            return Err(conflict(
                format!("filesystem.{key}"),
                "expected an array".into(),
            ));
        };
        for (i, item) in items.iter().enumerate() {
            let Some(p) = entry_path(item) else {
                continue;
            };
            let hits = grants
                .read
                .iter()
                .map(|g| (g, "read"))
                .chain(grants.allow.iter().map(|g| (g, "allow")));
            for (g, hecaton_level) in hits {
                if overlaps(&p, g) && hecaton_level != user_level {
                    return Err(conflict(
                        format!("filesystem.{key}[{i}]"),
                        format!(
                            "{} overlaps hecaton {hecaton_level} path {}",
                            p.display(),
                            g.display()
                        ),
                    ));
                }
            }
        }
    }
    Ok(())
}

pub fn write_profile(
    id: &AgentId,
    paths: &AgentPaths,
    profile: &Value,
) -> Result<(), MaterializeError> {
    let bytes = serde_json::to_vec_pretty(profile).unwrap_or_default();
    // 0600: the profile is the sandbox's boundary, and a writable or
    // widely readable one is a map of every path the agent may reach.
    write_atomic(&paths.profile, &bytes, 0o600).map_err(|e| MaterializeError::Io {
        id: id.to_string(),
        path: paths.profile.clone(),
        message: e.to_string(),
    })
}

pub fn validate_profile(
    tools: &ToolPaths,
    id: &AgentId,
    paths: &AgentPaths,
) -> Result<(), MaterializeError> {
    Cmd::new(&tools.nono)
        .args([
            "-s",
            "profile",
            "validate",
            &paths.profile.display().to_string(),
        ])
        .env("HOME", paths.nono_home.display().to_string())
        .log(&paths.logs.join("nono.validate.log"))
        .run()
        .map(|_| ())
        .map_err(|f| MaterializeError::Tool {
            id: id.to_string(),
            tool: f.tool,
            subcommand: "profile validate".into(),
            args: f.args,
            stderr: if f.stderr.trim().is_empty() {
                "profile invalid".into()
            } else {
                f.stderr
            },
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> (AgentId, Grants, BTreeMap<String, String>) {
        let layout = StateLayout::from_env(Path::new("/h"), |_| None);
        let id: AgentId = "f/c/a".parse().unwrap();
        let paths = layout.agent(&id);
        let crew = layout.crew(&id.crew_ref());
        let grants = hecaton_grants(&paths, &crew, &layout);
        (
            id,
            grants,
            BTreeMap::from([("HOME".to_string(), paths.home.display().to_string())]),
        )
    }

    #[test]
    fn base_profile_has_the_required_grants_env_and_port() {
        let (id, grants, env) = fixture();
        let p = render_profile(&id, &grants, 7643, &env, &json!({})).unwrap();
        assert_eq!(p["meta"]["name"], "hecaton-f-c-a");
        assert_eq!(p["filesystem"]["read"][0], "/usr");
        assert_eq!(p["filesystem"]["read"][5], "/h/.local/share/hecaton/mise");
        assert_eq!(
            p["filesystem"]["allow"][2],
            "/h/.local/state/hecaton/fleets/f/crews/c/repo/.git"
        );
        assert_eq!(p["workdir"]["access"], "none");
        assert_eq!(p["network"]["connect_port"], json!([7643]));
        assert_eq!(p["environment"]["deny_vars"], json!(["*"]));
        assert_eq!(
            p["environment"]["set_vars"]["HOME"],
            "/h/.local/state/hecaton/fleets/f/crews/c/agents/a/home"
        );
    }

    #[test]
    fn user_block_merges_with_extends_semantics() {
        let (id, grants, env) = fixture();
        let user = json!({ "network": { "block": true, "connect_port": [7643, 8080] }, "filesystem": { "read": ["/opt/data"] }, "extends": "default" });
        let p = render_profile(&id, &grants, 7643, &env, &user).unwrap();
        assert_eq!(p["network"]["block"], true);
        assert_eq!(
            p["network"]["connect_port"],
            json!([7643, 8080]),
            "append + dedupe"
        );
        assert_eq!(
            p["filesystem"]["read"].as_array().unwrap().last().unwrap(),
            "/opt/data"
        );
        assert_eq!(p["extends"], "default");
    }

    #[test]
    fn owned_keys_and_overlapping_grants_are_rejected_with_paths() {
        let (id, grants, env) = fixture();
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "environment": { "set_vars": { "X": "1" } } }),
        )
        .unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.environment: hecaton-owned; set variables through `env` instead"
        );
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "filesystem": { "read": ["/x", "/h/.local/state/hecaton/fleets/f/crews/c/agents/a/home/.claude"] } }),
        )
        .unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.filesystem.read[1]: /h/.local/state/hecaton/fleets/f/crews/c/agents/a/home/.claude overlaps hecaton allow path /h/.local/state/hecaton/fleets/f/crews/c/agents/a/home"
        );
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "filesystem": { "allow": [{ "path": "/usr/local" }] } }),
        )
        .unwrap_err();
        assert!(e.to_string().contains("overlaps hecaton read path /usr"));
        // same level is fine
        assert!(
            render_profile(
                &id,
                &grants,
                1,
                &env,
                &json!({ "filesystem": { "read": ["/usr/share"] } })
            )
            .is_ok()
        );
    }

    #[test]
    fn malformed_filesystem_shapes_are_rejected() {
        let (id, grants, env) = fixture();
        let e =
            render_profile(&id, &grants, 1, &env, &json!({ "filesystem": "nope" })).unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.filesystem: expected an object"
        );
        let e = render_profile(
            &id,
            &grants,
            1,
            &env,
            &json!({ "filesystem": { "read": "/opt/data" } }),
        )
        .unwrap_err();
        assert_eq!(
            e.to_string(),
            "f/c/a: sandbox.filesystem.read: expected an array"
        );
    }

    #[test]
    fn merge_is_idempotent() {
        let base = json!({ "a": [1, 2], "b": { "c": 1 } });
        let user = json!({ "a": [2, 3], "b": { "d": 2 } });
        let once = merge_profile(base.clone(), &user);
        let twice = merge_profile(once.clone(), &user);
        assert_eq!(once, twice);
        assert_eq!(once, json!({ "a": [1, 2, 3], "b": { "c": 1, "d": 2 } }));
    }
}
