//! The agent's tool table (Phase 2 spec §4.2 step 3, P2-8): system pins ⊕
//! user `tools`, installed by the daemon into the shared data dir.

use std::collections::BTreeMap;
use std::path::Path;

use hecaton_core::{AgentId, MaterializeError};

use crate::fsutil::write_atomic;
use crate::layout::{AgentPaths, StateLayout};
use crate::tools::{Cmd, ToolPaths};

/// This repository's own pins, embedded at build time so a fresh install can
/// launch `claude` without the user writing a system tool table first.
pub const EMBEDDED_MISE_TOML: &str = include_str!("../../../mise.toml");

/// Tools an agent inherits from the embedded table. `gh` is only emitted
/// when the crew authenticates through it.
const INHERITED: &[&str] = &["claude", "gh"];

fn tools_table(toml_text: &str) -> Result<BTreeMap<String, String>, String> {
    let doc: toml::Table = toml_text
        .parse()
        .map_err(|e: toml::de::Error| e.to_string())?;
    let mut out = BTreeMap::new();
    if let Some(toml::Value::Table(tools)) = doc.get("tools") {
        for (k, v) in tools {
            let version = match v {
                toml::Value::String(s) => s.clone(),
                toml::Value::Table(t) => match t.get("version") {
                    Some(toml::Value::String(s)) => s.clone(),
                    _ => return Err(format!("tools.{k}: expected a version string")),
                },
                _ => return Err(format!("tools.{k}: expected a version string")),
            };
            out.insert(k.clone(), version);
        }
    }
    Ok(out)
}

pub fn embedded_system_tools() -> BTreeMap<String, String> {
    tools_table(EMBEDDED_MISE_TOML)
        .unwrap_or_default()
        .into_iter()
        .filter(|(k, _)| INHERITED.contains(&k.as_str()))
        .collect()
}

/// `$XDG_CONFIG_HOME/hecaton/mise.toml` `[tools]` if the file exists, else
/// the embedded default.
pub fn system_tools(
    layout: &StateLayout,
    id: &AgentId,
) -> Result<BTreeMap<String, String>, MaterializeError> {
    let path = layout.system_mise_toml();
    match std::fs::read_to_string(&path) {
        Ok(text) => tools_table(&text).map_err(|message| MaterializeError::Io {
            id: id.to_string(),
            path,
            message,
        }),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(embedded_system_tools()),
        Err(e) => Err(MaterializeError::Io {
            id: id.to_string(),
            path,
            message: e.to_string(),
        }),
    }
}

/// System ⊕ user ⊕, when `with_gh`, `gh = <hecaton's pinned gh>` (spec §4.2
/// step 3): a `git.auth: gh` crew always gets a `gh` entry even if an
/// admin's system table omits one, falling back to the embedded pin; system
/// and user values still win over that fallback. Without `with_gh` the
/// *system* `gh` is dropped — a `gh` the user asked for in `settings.tools`
/// is merged in afterwards and always survives, since a crew that does not
/// use gh for git auth may still want the CLI.
pub fn render_mise_toml(
    id: &AgentId,
    system: &BTreeMap<String, String>,
    user: &BTreeMap<String, String>,
    with_gh: bool,
) -> String {
    let mut table: BTreeMap<&str, &str> = system
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();
    if !with_gh {
        table.remove("gh");
    }
    for (k, v) in user {
        table.insert(k, v);
    }
    let embedded_gh = embedded_system_tools().get("gh").cloned();
    if with_gh
        && !table.contains_key("gh")
        && let Some(pin) = &embedded_gh
    {
        table.insert("gh", pin.as_str());
    }
    let mut out =
        format!("# generated by hecaton for {id}; edit the fleet file, not this\n[tools]\n");
    for (k, v) in table {
        out.push_str(&format!("{} = {:?}\n", toml_key(k), v));
    }
    out
}

fn toml_key(k: &str) -> String {
    if k.chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        k.to_string()
    } else {
        format!("{k:?}")
    }
}

pub fn mise_env(paths: &AgentPaths, layout: &StateLayout) -> BTreeMap<String, String> {
    let s = |p: std::path::PathBuf| p.display().to_string();
    BTreeMap::from([
        (
            "MISE_GLOBAL_CONFIG_FILE".to_string(),
            s(paths.mise_toml.clone()),
        ),
        ("MISE_DATA_DIR".to_string(), s(layout.mise_data_dir())),
        ("MISE_CONFIG_DIR".to_string(), s(paths.mise_config_dir())),
        ("MISE_STATE_DIR".to_string(), s(paths.mise_state_dir())),
        ("MISE_CACHE_DIR".to_string(), s(paths.mise_cache_dir())),
        ("MISE_YES".to_string(), "1".to_string()),
        ("MISE_QUIET".to_string(), "1".to_string()),
        // never install from inside the sandbox; the daemon installs beforehand
        ("MISE_AUTO_INSTALL".to_string(), "false".to_string()),
    ])
}

pub struct Toolchain<'a> {
    pub tools: &'a ToolPaths,
    pub layout: &'a StateLayout,
}

impl Toolchain<'_> {
    /// Writes `mise.toml`; returns whether its content changed.
    pub fn write(
        &self,
        id: &AgentId,
        paths: &AgentPaths,
        system: &BTreeMap<String, String>,
        user: &BTreeMap<String, String>,
        with_gh: bool,
    ) -> Result<bool, MaterializeError> {
        let text = render_mise_toml(id, system, user, with_gh);
        if std::fs::read_to_string(&paths.mise_toml).ok().as_deref() == Some(text.as_str()) {
            return Ok(false);
        }
        write_atomic(&paths.mise_toml, text.as_bytes(), 0o644).map_err(|e| {
            MaterializeError::Io {
                id: id.to_string(),
                path: paths.mise_toml.clone(),
                message: e.to_string(),
            }
        })?;
        Ok(true)
    }

    /// `mise trust` then `mise install`, unsandboxed, into the shared data dir.
    /// Runs with `cwd=/` so no project `mise.toml` on the way up (the repo
    /// hecaton itself sits in, during tests) is discovered: only the agent's
    /// global file counts.
    pub fn install(&self, id: &AgentId, paths: &AgentPaths) -> Result<(), MaterializeError> {
        let env = mise_env(paths, self.layout);
        let log = paths.logs.join("mise.toolchain.log");
        let run = |args: &[&str]| {
            Cmd::new(&self.tools.mise)
                .args(args.iter().copied())
                .envs(&env)
                .cwd(Path::new("/"))
                .log(&log)
                .run()
                .map(|_| ())
                .map_err(|f| MaterializeError::Tool {
                    id: id.to_string(),
                    tool: f.tool,
                    subcommand: f.subcommand,
                    args: f.args,
                    stderr: f.stderr,
                })
        };
        run(&["trust", &paths.mise_toml.display().to_string()])?;
        run(&["install"])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn id() -> AgentId {
        "payments/backend/alice".parse().unwrap()
    }

    #[test]
    fn embedded_table_carries_only_claude_and_gh_pins() {
        let t = embedded_system_tools();
        assert_eq!(t.keys().collect::<Vec<_>>(), vec!["claude", "gh"]);
        assert!(t["claude"].chars().next().unwrap().is_ascii_digit());
    }

    #[test]
    fn tools_table_accepts_string_and_table_forms() {
        let t = tools_table(
            "[tools]\nrust = { version = \"1.98.1\", components = [\"clippy\"] }\n\"cargo:x\" = \"1.0.0\"\n",
        )
        .unwrap();
        assert_eq!(t["rust"], "1.98.1");
        assert_eq!(t["cargo:x"], "1.0.0");
        assert!(
            tools_table("[tools]\nx = 3\n")
                .unwrap_err()
                .starts_with("tools.x")
        );
    }

    #[test]
    fn render_merges_user_over_system_and_drops_gh_without_auth() {
        let system = BTreeMap::from([
            ("claude".to_string(), "2.0.0".to_string()),
            ("gh".to_string(), "2.100.0".to_string()),
        ]);
        let user = BTreeMap::from([
            ("node".to_string(), "22.11.0".to_string()),
            ("claude".to_string(), "2.1.0".to_string()),
        ]);
        let with = render_mise_toml(&id(), &system, &user, true);
        assert_eq!(
            with,
            "# generated by hecaton for payments/backend/alice; edit the fleet file, not this\n[tools]\nclaude = \"2.1.0\"\ngh = \"2.100.0\"\nnode = \"22.11.0\"\n"
        );
        let without = render_mise_toml(&id(), &system, &user, false);
        assert!(!without.contains("gh ="));
        let quoted = render_mise_toml(
            &id(),
            &BTreeMap::new(),
            &BTreeMap::from([("cargo:x".to_string(), "1.0.0".to_string())]),
            false,
        );
        assert!(quoted.contains("\"cargo:x\" = \"1.0.0\""));
    }

    #[test]
    fn with_gh_inserts_the_embedded_pin_when_the_system_table_lacks_it() {
        let system = BTreeMap::from([("claude".to_string(), "2.0.0".to_string())]);
        let embedded_gh = embedded_system_tools()["gh"].clone();
        let with = render_mise_toml(&id(), &system, &BTreeMap::new(), true);
        assert!(
            with.contains(&format!("gh = \"{embedded_gh}\"")),
            "expected embedded gh pin in {with}"
        );
        let without = render_mise_toml(&id(), &system, &BTreeMap::new(), false);
        assert!(!without.contains("gh ="));
    }

    #[test]
    fn system_tools_prefers_the_config_file() {
        let dir = tempfile::tempdir().unwrap();
        let layout = StateLayout::from_env(dir.path(), |_| None);
        assert_eq!(
            system_tools(&layout, &id()).unwrap(),
            embedded_system_tools()
        );
        std::fs::create_dir_all(&layout.config_root).unwrap();
        std::fs::write(layout.system_mise_toml(), "[tools]\nclaude = \"9.9.9\"\n").unwrap();
        assert_eq!(system_tools(&layout, &id()).unwrap()["claude"], "9.9.9");
    }

    #[test]
    fn write_reports_changes() {
        let dir = tempfile::tempdir().unwrap();
        let layout = StateLayout::from_env(dir.path(), |_| None);
        let tools = ToolPaths {
            git: "/g".into(),
            gh: "/h".into(),
            mise: "/m".into(),
            nono: "/n".into(),
            tmux: "/t".into(),
            hecaton: "/x".into(),
        };
        let tc = Toolchain {
            tools: &tools,
            layout: &layout,
        };
        let paths = layout.agent(&id());
        let sys = embedded_system_tools();
        assert!(
            tc.write(&id(), &paths, &sys, &BTreeMap::new(), false)
                .unwrap()
        );
        assert!(
            !tc.write(&id(), &paths, &sys, &BTreeMap::new(), false)
                .unwrap()
        );
        assert!(
            tc.write(&id(), &paths, &sys, &BTreeMap::new(), true)
                .unwrap()
        );
    }
}
